# Generated by Django 3.2.24 on 2024-02-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
